### ISSUE TITLE
Not sure how to apply LifecycleBasePlugin

### ISSUE THREAD

**Issue by isuPatches** [aaschmid/gradle-cpd-plugin#37]
Hey there, I'm having some trouble with the 1.3 version.  I have an Android library and don't understand how to fix this:

```
WARNING: Due to the absence of 'LifecycleBasePlugin' on project ':wisefy'
the provider(task cpdCheck, class de.aaschmid.gradle.plugins.cpd.Cpd) could not be added to task graph and therefore will not be executed.
SUGGESTION: add a dependency to cpdCheck manually to a subprojects 'check'
task, e.g. to project ':wisefy' using

    check.dependsOn('cpdCheck')

or to project ':wisefy' using

    project(':wisefy') {
        plugins.withType(LifecycleBasePlugin) { // <- just required if 'java' plugin is applied within subproject
            check.dependsOn(cpdCheck)
        }
    }

```

**Comment by aaschmid** [comment]
This is indeed strange. 

Reason: Until version 1.2 the `cpdCheck` was attached while `JavaBasePlugin` was applied. In 1.3 I attached that behavior to `LifecycleBasePlugin`. This should not change anything since `JavaBasePlugin` applies `BasePlugin` which applies `LifecycleBasePlugin` ...

@isuPatches: Thanks for reporting, just checked out your referenced project and can perfectly reproduce the behavior. Working on understanding why it fails ...

**Comment by aaschmid** [comment]
Good news @isuPatches: `cpdCheck` is executed even if the above mentioned warning is shown. 

So this issues drills down to an incorrect warning. Do you agree?

**Comment by isuPatches** [comment]
👍 Yes, that's the same behavior I'm seeing locally.  Thanks for the quick investigation!

**Comment by aaschmid** [comment]
Found the reason: While switching to `TaskProvider` in order to configuration avoidance, I do no longer have the actual task and I am assuming that CPD plugin is always applied on the root project. Latter could be reasonable because Copy-Paste-Detection should be applied to the whole (main) source code.
